import type { Artifact, Mechanic, Twist } from "@/lib/types";

/**
 * The technical crux of a problem. `requires` drives the doability score, so
 * these categories must be honest about what someone actually needs to know.
 */
export const MECHANICS: Mechanic[] = [
  {
    id: "fuzzy-match",
    artifacts: ["webapp", "cli", "library", "dashboard", "bot"],
    label: "fuzzy matching and ranking",
    requires: ["backend", "data"],
    difficulty: 2,
    requirement: "Match and rank records that disagree on spelling, format and casing, and explain why each match scored the way it did.",
    teaches: "string distance metrics and why exact-match thinking fails on real data",
  },
  {
    id: "structuring",
    artifacts: ["cli", "pipeline", "library", "webapp", "study"],
    label: "turning messy input into structure",
    requires: ["data"],
    difficulty: 2,
    requirement: "Ingest the messiest real version of the source and emit a clean, validated schema, flagging rows it could not parse rather than silently dropping them.",
    teaches: "defensive parsing and the discipline of never discarding data you failed to understand",
  },
  {
    id: "timeseries",
    artifacts: ["dashboard", "webapp", "study", "pipeline", "mobile"],
    label: "finding patterns over time",
    requires: ["data"],
    difficulty: 2,
    requirement: "Detect trends, streaks and outliers over time and state plainly how confident the answer is given how little data exists.",
    teaches: "rolling windows, baselines, and honest uncertainty on small samples",
  },
  {
    id: "scheduling",
    artifacts: ["webapp", "cli", "bot", "library", "dashboard"],
    label: "constraint solving and scheduling",
    requires: ["backend", "systems"],
    difficulty: 3,
    requirement: "Produce a valid assignment under hard constraints, and when none exists, report the smallest set of constraints that would have to give.",
    teaches: "constraint modelling and how to fail informatively instead of just failing",
  },
  {
    id: "realtime",
    artifacts: ["webapp", "mobile", "bot"],
    label: "realtime sync between people",
    requires: ["backend", "frontend"],
    difficulty: 3,
    requirement: "Keep several people's views consistent as they act at the same time, and resolve conflicting edits without losing anyone's work.",
    teaches: "optimistic updates, conflict resolution and the cost of shared state",
  },
  {
    id: "search",
    artifacts: ["webapp", "cli", "extension", "library", "bot"],
    label: "search that understands intent",
    requires: ["backend", "data"],
    difficulty: 2,
    requirement: "Return the right result for a vague, misspelled or partial query, and rank results in an order the user would defend.",
    teaches: "indexing, relevance scoring and evaluating search quality rather than guessing at it",
  },
  {
    id: "classify",
    artifacts: ["model", "pipeline", "webapp", "bot", "cli"],
    label: "automatic classification",
    requires: ["ml", "data"],
    difficulty: 2,
    requirement: "Label incoming items automatically, report per-class accuracy honestly, and route low-confidence cases to a human instead of guessing.",
    teaches: "baselines, class imbalance and why accuracy alone is a misleading number",
  },
  {
    id: "recommend",
    artifacts: ["webapp", "model", "bot", "mobile"],
    label: "recommendation under sparse data",
    requires: ["ml", "data"],
    difficulty: 3,
    requirement: "Recommend well for a brand-new user with almost no history, and be able to explain any single recommendation in one sentence.",
    teaches: "the cold-start problem and why explainability beats a marginally better score",
  },
  {
    id: "vision",
    artifacts: ["model", "mobile", "webapp", "device"],
    label: "getting information out of images",
    requires: ["ml"],
    difficulty: 3,
    requirement: "Extract reliable information from photographs taken in bad light by people who are not photographers, and refuse confidently when the image is unusable.",
    teaches: "preprocessing, robustness to real-world input and knowing when to abstain",
  },
  {
    id: "nlp-extract",
    artifacts: ["model", "pipeline", "webapp", "cli", "extension"],
    label: "pulling meaning out of text",
    requires: ["ml", "data"],
    difficulty: 2,
    requirement: "Extract the specific facts that matter from long unstructured documents, and cite the exact span each fact came from.",
    teaches: "information extraction and building trust through traceability",
  },
  {
    id: "geo",
    artifacts: ["webapp", "mobile", "dashboard", "study"],
    label: "reasoning about places and routes",
    requires: ["data", "frontend"],
    difficulty: 2,
    requirement: "Work with real coordinates and networks, and handle the cases where the map is wrong or the data is missing for exactly the area that matters.",
    teaches: "spatial joins, projections and the politics of what maps leave out",
  },
  {
    id: "offline-sync",
    artifacts: ["mobile", "webapp", "library"],
    label: "working offline and reconciling later",
    requires: ["mobile", "backend"],
    difficulty: 3,
    requirement: "Stay fully usable with no connection for days, then reconcile cleanly when the connection returns, with no silent data loss.",
    teaches: "local-first architecture and the surprisingly hard problem of merge",
  },
  {
    id: "pipeline",
    artifacts: ["pipeline", "cli", "dashboard", "study"],
    label: "a pipeline that runs itself",
    requires: ["ops", "data"],
    difficulty: 2,
    requirement: "Run unattended on a schedule, recover from partial failures, and make it obvious from the outside when it has silently stopped working.",
    teaches: "idempotency, retries and observability for things nobody is watching",
  },
  {
    id: "perf",
    artifacts: ["cli", "library", "webapp", "extension"],
    label: "making something fast enough to feel instant",
    requires: ["systems"],
    difficulty: 3,
    requirement: "Hold a hard latency budget on a realistically large input, and prove it with a benchmark rather than a feeling.",
    teaches: "profiling, algorithmic complexity and measuring before optimising",
  },
  {
    id: "parser",
    artifacts: ["cli", "library", "pipeline", "extension"],
    label: "parsing a format nobody standardised",
    requires: ["systems", "data"],
    difficulty: 3,
    requirement: "Correctly read the ugly real-world format including its undocumented variations, with a test suite built from genuinely broken examples.",
    teaches: "grammar design, tokenising and the value of a hostile test corpus",
  },
  {
    id: "viz",
    artifacts: ["dashboard", "webapp", "study", "extension"],
    label: "making a hard truth visible in one screen",
    requires: ["frontend", "design"],
    difficulty: 2,
    requirement: "Present the finding so that a busy, sceptical person understands it in under thirty seconds without a legend lecture.",
    teaches: "encoding choices, visual hierarchy and designing for a hostile reader",
  },
  {
    id: "workflow",
    artifacts: ["webapp", "bot", "mobile", "dashboard"],
    label: "modelling a messy human workflow",
    requires: ["backend", "design"],
    difficulty: 2,
    requirement: "Model how the work is actually done, including the exceptions and the informal handoffs, rather than how a tidy diagram says it should be.",
    teaches: "state machines, edge cases and designing around people rather than against them",
  },
  {
    id: "capture",
    artifacts: ["mobile", "webapp", "bot", "device"],
    label: "capturing data at the moment it happens",
    requires: ["mobile", "design"],
    difficulty: 2,
    requirement: "Make recording an observation take under five seconds with cold hands and one thumb, because anything slower simply will not happen.",
    teaches: "interaction cost and why the best data model loses to the fastest input",
  },
  {
    id: "sensor",
    artifacts: ["device", "dashboard", "mobile"],
    label: "reading the physical world",
    requires: ["hardware"],
    difficulty: 3,
    requirement: "Take a noisy physical measurement, calibrate it, and produce a number somebody would be willing to act on.",
    teaches: "signal noise, calibration drift and the gap between a reading and a fact",
  },
  {
    id: "simulate",
    artifacts: ["webapp", "dashboard", "study", "game"],
    label: "simulating what would happen",
    requires: ["systems", "data"],
    difficulty: 3,
    requirement: "Let someone change an assumption and immediately see the consequence, with the model's assumptions visible rather than buried.",
    teaches: "modelling, sensitivity analysis and communicating what a simulation cannot tell you",
  },
  {
    id: "privacy",
    artifacts: ["webapp", "cli", "library", "extension", "mobile"],
    label: "handling data that must not leak",
    requires: ["security", "backend"],
    difficulty: 3,
    requirement: "Handle genuinely sensitive information such that a breach of any single component still does not expose it.",
    teaches: "threat modelling, minimisation and designing for the failure you did not plan",
  },
  {
    id: "gameloop",
    artifacts: ["game", "webapp", "mobile"],
    label: "a loop that stays interesting",
    requires: ["gamedev"],
    difficulty: 2,
    requirement: "Build a core loop that is still worth doing on the twentieth attempt, and instrument it so you can see where people stop.",
    teaches: "pacing, feedback loops and playtesting as a measurement discipline",
  },

  // --- Non-software engineering ----------------------------------------
  // Each of these requires exactly one of the new engineering categories,
  // never combined with another - unlike the software mechanics above,
  // whose cross-category combos (e.g. ml + hardware) are real skill
  // overlaps within one field. Mechanical and electrical and civil are
  // separate disciplines; requiring more than one at once would wrongly
  // block a person who only has one of them.
  {
    id: "structural",
    artifacts: ["prototype", "analysis"],
    label: "sizing a structure or mechanism so it survives real loads",
    requires: ["mechanical"],
    difficulty: 3,
    requirement: "Size the part against a real, stated load case with a safety factor you can justify, not a number that merely looks strong enough.",
    teaches: "stress analysis and the difference between looking strong and being sized",
  },
  {
    id: "circuit-design",
    artifacts: ["prototype", "analysis", "device"],
    label: "designing a circuit that behaves predictably",
    requires: ["electrical"],
    difficulty: 3,
    requirement: "Design and build a circuit that still works once it leaves the ideal conditions of a datasheet - real tolerances, real noise, real temperature.",
    teaches: "circuit analysis and the gap between a schematic and the physical build",
  },
  {
    id: "site-systems",
    artifacts: ["analysis", "study"],
    label: "designing for the site as it actually is, not an idealised one",
    requires: ["civil"],
    difficulty: 3,
    requirement: "Base the design on the real conditions of the specific site - its soil, its water, its loads - not a generic textbook assumption.",
    teaches: "site-specific load paths and designing for the worst realistic case, not the average one",
  },
  {
    id: "process-design",
    artifacts: ["analysis", "study"],
    label: "engineering a process that stays safe and controllable at scale",
    requires: ["chemical"],
    difficulty: 3,
    requirement: "Show the mass and energy balance for the process at the scale it would actually run, and name the failure mode that only appears once you leave the lab bench.",
    teaches: "why lab-scale success does not guarantee plant-scale success",
  },
  {
    id: "flight-dynamics",
    artifacts: ["analysis", "prototype"],
    label: "keeping something stable while it moves through a fluid",
    requires: ["aerospace"],
    difficulty: 3,
    requirement: "Show the stability margin under a real disturbance, not just steady, ideal conditions.",
    teaches: "aerodynamics, stability margins and the cost of being wrong in the air",
  },
  {
    id: "biomech-design",
    artifacts: ["prototype", "analysis"],
    label: "designing for a body that will not read the spec sheet",
    requires: ["biomedical"],
    difficulty: 3,
    requirement: "Design around real human variation - not one idealised body - and be explicit about who it was and wasn't tested with.",
    teaches: "biocompatibility, human variability and designing around a regulator's questions",
  },
  {
    id: "environmental-system",
    artifacts: ["analysis", "study"],
    label: "engineering within a hard environmental limit",
    requires: ["environmental"],
    difficulty: 2,
    requirement: "Measure against a real, named limit or standard, not a vague sense of 'better than before.'",
    teaches: "environmental constraints, monitoring and designing for compliance over time, not a single test",
  },
  {
    id: "manufacturability",
    artifacts: ["prototype", "analysis"],
    label: "designing something that can be built the same way twice",
    requires: ["industrial"],
    difficulty: 2,
    requirement: "Design for the tenth unit, not just the first - state the tolerances and the process, and show what breaks if either drifts.",
    teaches: "process capability and designing for the person who builds the tenth one, not just the first",
  },
];

/** The shape of the thing that ships. */
export const ARTIFACTS: Artifact[] = [
  {
    id: "webapp",
    label: "Web app",
    phrase: "a web app",
    requires: ["frontend"],
    nice: ["backend", "design"],
    weight: 2,
    deliverable: "a deployed web app anyone can open with a link, with no install step",
  },
  {
    id: "cli",
    label: "CLI tool",
    phrase: "a command-line tool",
    requires: ["systems"],
    nice: ["backend"],
    weight: 1,
    deliverable: "a single-command tool with a real --help, sensible defaults and a README someone could follow cold",
  },
  {
    id: "mobile",
    label: "Mobile app",
    phrase: "a mobile app",
    requires: ["mobile"],
    nice: ["design", "backend"],
    weight: 3,
    deliverable: "an installable app that works one-handed on a cheap phone",
  },
  {
    id: "bot",
    label: "Chat bot / automation",
    phrase: "a chat bot",
    requires: ["backend"],
    nice: ["ops"],
    weight: 1,
    deliverable: "a bot in the chat tool the group already uses, requiring no new app from anyone",
  },
  {
    id: "dashboard",
    label: "Dashboard",
    phrase: "a dashboard",
    requires: ["frontend", "data"],
    nice: ["design"],
    weight: 2,
    deliverable: "a single screen that answers the question without anyone needing to be trained on it",
  },
  {
    id: "pipeline",
    label: "Data pipeline",
    phrase: "an automated data pipeline",
    requires: ["data"],
    nice: ["ops", "backend"],
    weight: 2,
    deliverable: "a scheduled job that produces a clean, documented dataset plus a status page proving it ran",
  },
  {
    id: "library",
    label: "Library / package",
    phrase: "an open-source library",
    requires: ["backend"],
    nice: ["systems"],
    weight: 2,
    deliverable: "a published package with tests, documentation and a worked example someone can copy",
  },
  {
    id: "model",
    label: "Model + interface",
    phrase: "a trained model with a usable interface",
    requires: ["ml"],
    nice: ["backend", "frontend"],
    weight: 3,
    deliverable: "a model with an honest evaluation writeup and an interface a non-expert can actually try",
  },
  {
    id: "device",
    label: "Physical device",
    phrase: "a physical device",
    requires: ["hardware"],
    nice: ["systems"],
    weight: 3,
    deliverable: "a working physical build with a wiring diagram and a parts list under a stated budget",
  },
  {
    id: "game",
    label: "Game / playable",
    phrase: "a small playable game",
    requires: ["gamedev"],
    nice: ["design"],
    weight: 2,
    deliverable: "a playable build that a stranger can finish without you sitting next to them",
  },
  {
    id: "extension",
    label: "Browser extension",
    phrase: "a browser extension",
    requires: ["frontend"],
    nice: ["design"],
    weight: 1,
    deliverable: "an installable extension that improves a site the person already uses every day",
  },
  {
    id: "study",
    label: "Investigation + writeup",
    phrase: "an investigation with a published writeup",
    requires: ["data"],
    nice: ["design"],
    weight: 1,
    deliverable: "a public writeup with reproducible analysis, the raw data, and a finding somebody would argue with",
  },
  {
    id: "prototype",
    label: "Physical prototype",
    phrase: "a physical prototype",
    // Deliberately empty - the paired mechanic (structural, circuit-design,
    // biomech-design, ...) is what supplies the actual discipline
    // requirement. This artifact is just the shipping format.
    requires: [],
    nice: ["industrial"],
    weight: 3,
    deliverable: "a working physical prototype with CAD files or drawings, a bill of materials, and evidence it meets a stated spec",
  },
  {
    id: "analysis",
    label: "Engineering analysis",
    phrase: "an engineering analysis",
    requires: [],
    nice: ["data"],
    weight: 2,
    deliverable: "a calculation- or simulation-backed report with its assumptions stated up front, checked against a hand-calculation or a real measurement",
  },
];

/**
 * Constraints that push a problem somewhere non-obvious. These are what stop
 * generated problems from collapsing into "build a CRUD app for X".
 */
export const TWISTS: Twist[] = [
  {
    id: "offline",
    text: "It has to keep working with no internet connection at all, and reconcile later.",
    teaches: "local-first design and merge conflict resolution",
    excludeArtifacts: ["prototype", "analysis"],
  },
  {
    id: "no-account",
    text: "Nobody should have to create an account to get value out of it.",
    teaches: "designing trust and continuity without identity",
    excludeArtifacts: ["prototype", "analysis"],
  },
  {
    id: "zero-cost",
    text: "Running costs must be zero forever, so no paid APIs and no always-on server.",
    teaches: "static-first architecture and creative resource constraints",
  },
  {
    id: "ten-seconds",
    text: "The whole interaction has to be finishable in under ten seconds, one-handed.",
    teaches: "ruthless scope reduction and interaction cost",
  },
  {
    id: "explainable",
    text: "Every automated decision has to come with a plain-language reason a sceptic would accept.",
    teaches: "explainability and designing for justified trust",
    excludeArtifacts: ["prototype", "analysis"],
  },
  {
    id: "one-file",
    text: "The entire thing has to fit in a single file that someone could read in one sitting.",
    teaches: "radical simplicity and resisting premature abstraction",
    excludeArtifacts: ["prototype", "analysis"],
  },
  {
    id: "cheap-phone",
    text: "It has to be usable on a five-year-old budget phone on a bad connection.",
    teaches: "performance budgets and designing for the constrained majority",
    excludeArtifacts: ["prototype", "analysis"],
  },
  {
    id: "no-training",
    text: "A new person must be able to use it correctly with no training and no documentation.",
    teaches: "affordances and self-evident interface design",
  },
  {
    id: "keyboard-only",
    text: "It must be fully operable by keyboard and screen reader alone.",
    teaches: "real accessibility rather than retrofitted accessibility",
    excludeArtifacts: ["prototype", "analysis"],
  },
  {
    id: "hostile-data",
    text: "The input data will be incomplete, contradictory and occasionally wrong, and it must degrade gracefully.",
    teaches: "defensive design and graceful degradation",
  },
  {
    id: "handover",
    text: "It has to survive being handed to a completely new person next year with no handover meeting.",
    teaches: "documentation, legibility and building for succession",
  },
  {
    id: "private",
    text: "The sensitive data must never leave the user's own device.",
    teaches: "client-side processing and privacy-preserving architecture",
    excludeArtifacts: ["prototype", "analysis"],
  },
  {
    id: "no-new-tool",
    text: "It cannot ask anyone to adopt a new tool, so it has to work inside what they already use.",
    teaches: "integration-first thinking and meeting users where they are",
    excludeArtifacts: ["prototype", "analysis"],
  },
  {
    id: "one-screen",
    text: "The output has to fit on one screen with no scrolling and no tabs.",
    teaches: "information density and editorial judgement",
  },
  {
    id: "audit",
    text: "Every change must be reversible and leave a trail showing who changed what and why.",
    teaches: "event sourcing and designing for accountability",
  },
  {
    id: "two-hundred",
    text: "It has to still be correct and fast at two hundred times the data you test with.",
    teaches: "scale testing and finding the bottleneck before users do",
  },
  {
    id: "margin",
    text: "It has to keep working even if a real measurement comes in twenty percent worse than your best estimate.",
    teaches: "safety factors and designing for the estimate being wrong, not just for the estimate",
  },
  {
    id: "verify-by-hand",
    text: "Someone with none of your tools or software must be able to check your answer is reasonable by hand.",
    teaches: "sanity-checking, order-of-magnitude reasoning and distrust of a number you can't independently verify",
  },
];

export const MECHANIC_BY_ID = new Map(MECHANICS.map((m) => [m.id, m]));
export const ARTIFACT_BY_ID = new Map(ARTIFACTS.map((a) => [a.id, a]));
export const TWIST_BY_ID = new Map(TWISTS.map((t) => [t.id, t]));
